export default {
  User: 'mdi:account',
  UserAccount: 'mdi:account-box-outline',
  PrivilegedUserAccount: 'mdi:account-key',
  /* Artifacts */
  DigitalArtifact: 'mdi:file-document-outline',
  DefensiveTechnique: 'mdi:shield-outline',
  OffensiveTechnique: 'mdi:sword-cross',
  CodeRepository: 'mdi:source-repository',
  StaticAnalysisTool: 'mdi:code-tags-check',
  CredentialScrubbing: 'mdi:key-remove',
  AssetVulnerabilityEnumeration: 'mdi:shield-search',
  DynamicAnalysisTool: 'mdi:code-braces-box',
  TestExecutionTool: 'mdi:test-tube',
  FileFormatVerification: 'mdi:file-check-outline',

  /* Development and testing tools */
  DeveloperApplication: 'mdi:code-braces',
  Compiler: 'mdi:cog-transfer-outline',
  UnitTestExecutionTool: 'mdi:flask-outline',
  IntegrationTestExecutionTool: 'mdi:flask-round-bottom-outline',
  SourceCodeAnalyzerTool: 'mdi:magnify-scan',
  VersionControlTool: 'mdi:source-branch',
  SoftwarePackagingTool: 'mdi:package-variant',
  ContainerBuildTool: 'mdi:cube-scan',

  /* Defensive techniques */
  FileAnalysis: 'mdi:file-eye-outline',
  FileHashing: 'mdi:pound-box-outline',
  FileIntegrityMonitoring: 'mdi:file-find-outline',
  FileEncryption: 'mdi:file-lock-outline',
  MessageEncryption: 'mdi:email-lock',
  NetworkTrafficFiltering: 'mdi:filter-outline',
  ExecutableAllowlisting: 'mdi:format-list-checks',
  ExecutableDenylisting: 'mdi:playlist-remove',
  CredentialRotation: 'mdi:key-change',
  CredentialRevocation: 'mdi:key-minus',
  AccountLocking: 'mdi:account-lock',
  SoftwareUpdate: 'mdi:update',
  /* Credentials and Access Control */
  Credential: 'mdi:key-chain-variant',
  PrivateKey: 'mdi:key',
  PublicKey: 'mdi:key-outline',
  /* checkov:skip=CKV_SECRET_6: This is an icon name. */
  Password: 'mdi:form-textbox-password',
  'Multi-factorAuthentication': 'mdi:two-factor-authentication',
  ServiceApplication: 'mdi:application-cog-outline',
  AccessControlConfiguration: 'mdi:shield-account',
  Software: 'mdi:application-outline',
  Process: 'mdi:cog-play-outline',
  CodeAnalyzer: 'mdi:file-search-outline',
  /* Network and Communication */
  ComputerNetworkNode: 'mdi:server-network',
  Firewall: 'mdi:wall-fire',
  Router: 'mdi:router',
  WirelessRouter: 'mdi:router-wireless',
  Switch: 'mdi:hub-outline',
  IPAddress: 'mdi:ip',
  DNSServer: 'mdi:dns',
  DNSRecord: 'mdi:dns-outline',
  ProxyServer: 'mdi:swap-horizontal',
  ReverseProxyServer: 'mdi:arrow-decision-outline',
  VPNServer: 'mdi:vpn',
  WebApplicationFirewall: 'mdi:shield-network',
  /* Services */
  DatabaseServer: 'mdi:database-cog',
  Database: 'mdi:database',
  Volume: 'mdi:disk',
  WebServer: 'mdi:web',
  NetworkTimeServer: 'mdi:clock-time-four-outline',

  /* Software */
  ScheduledJob: 'mdi:calendar-clock',
  BuildTool: 'mdi:hammer-wrench',
  PhysicalLocation: 'mdi:map-marker',
  ContainerOrchestrationSoftware: 'mdi:kubernetes',

  /* Cloud and containers */
  CloudStorage: 'mdi:cloud-outline',
  CloudInstanceMetadata: 'mdi:cloud-tags',
  CloudConfiguration: 'mdi:cloud-cog-outline',
  ContainerImage: 'mdi:docker',

  /* DigitalArtifact subclasses */
  Storage: 'mdi:harddisk',
  File: 'mdi:file-outline',
  Directory: 'mdi:folder-outline',
  Log: 'mdi:text-box-outline',
  NetworkTraffic: 'mdi:transit-connection-variant',
  SystemCall: 'mdi:function-variant',
  Command: 'mdi:console',
  Session: 'mdi:account-clock-outline',
  HardwareDevice: 'mdi:chip',
  SoftwarePackage: 'mdi:package-variant-closed',
  ComputingImage: 'mdi:disc',
  LogFile: 'mdi:script-text-outline',
};
